[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-macro = "0.2.1"
paste = "1.0.9"
ast = { path = "../ast" }
thiserror = "1.0.37"
