[package]
name = "interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
gc = { version = "0.4.1", features = ["derive"] }
is-macro = "0.2.1"
paste = "1.0.9"
thiserror = "1.0.37"

[dev-dependencies]
parser = { path = "../parser" }
